-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.general_info
(
    id serial NOT NULL,
    appid integer NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    release character varying COLLATE pg_catalog."default" NOT NULL,
    estiamted_owners character varying COLLATE pg_catalog."default" NOT NULL,
    peak_ccu character varying COLLATE pg_catalog."default" NOT NULL,
    required_age character varying COLLATE pg_catalog."default" NOT NULL,
    price character varying COLLATE pg_catalog."default" NOT NULL,
    metacritic_score character varying COLLATE pg_catalog."default" NOT NULL,
    user_score character varying COLLATE pg_catalog."default" NOT NULL,
    average_playtime_forever character varying COLLATE pg_catalog."default" NOT NULL,
    average_playtime_two_weeks character varying COLLATE pg_catalog."default" NOT NULL,
    median_playtime_forever character varying COLLATE pg_catalog."default" NOT NULL,
    median_playtime_two_weeks character varying COLLATE pg_catalog."default" NOT NULL,
    developers character varying COLLATE pg_catalog."default" NOT NULL,
    publishers character varying COLLATE pg_catalog."default" NOT NULL,
    categories character varying COLLATE pg_catalog."default" NOT NULL,
    genres character varying COLLATE pg_catalog."default" NOT NULL,
    tags character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT general_info_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.revenue_data
(
    id serial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    release_date character varying COLLATE pg_catalog."default" NOT NULL,
    copies_sold character varying COLLATE pg_catalog."default" NOT NULL,
    price double precision NOT NULL,
    revenue double precision NOT NULL,
    avg_playtime double precision NOT NULL,
    review_score integer NOT NULL,
    publisher_class character varying COLLATE pg_catalog."default" NOT NULL,
    publishers character varying COLLATE pg_catalog."default" NOT NULL,
    developers character varying COLLATE pg_catalog."default" NOT NULL,
    steam_id integer NOT NULL,
    CONSTRAINT revenue_data_pkey PRIMARY KEY (id)
);
END;